version: '3'
services:
  mypostgres:
    image: 'postgres:latest'
    ports:
      - "8080:8080"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: discogs
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "5432:5432"
    depends_on:
      - mypostgres
