version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: discogs
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=localhost
      - PGDATABASE=discogs
      - PGPASSWORD=postgres
      - PGPORT=5432
    depends_on:
      - postgres
volumes:
  postgres_data:
