### BUILD image
FROM maven:3-jdk-11 as builder
# create app folder for sources
RUN mkdir -p /workspace
WORKDIR /workspace
COPY pom.xml /workspace
#Download all required dependencies into one layer
RUN mvn -B dependency:resolve dependency:resolve-plugins
#Copy source code
COPY src /workspace/src
# Build application
RUN mvn -B -f pom.xml clean package -DskipTests


FROM openjdk:11-jdk-slim
COPY --from=builder /workspace/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]